name: aid_robot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  page_view_dot_indicator: ^2.3.0
  get: ^4.3.8
  conditional_builder_null_safety: ^0.0.6
  #zego_uikit_prebuilt_call: ^3.3.7
  dropdown_button2: ^1.1.1
  flutter_screenutil: ^5.6.0
  flutter_svg: ^2.0.7
  easy_localization: ^3.0.2
  shared_preferences: ^2.0.15
  jwt_decoder: any
  smooth_page_indicator: ^1.1.0
  equatable: ^2.0.3
  http: ^0.13.6
  connectivity_plus: ^3.0.2
  dartz: ^0.10.1
  flutter_bloc: ^8.1.5
  get_it: ^7.2.0
  data_connection_checker_nulls: ^0.0.2
  http_interceptor: ^1.0.2
  image_picker: ^1.1.2
  lottie: any
  url_launcher: ^6.1.6
  overlay_support: ^2.1.0
  pinput: ^2.2.31
  carousel_slider: ^4.2.1
  bloc: ^8.1.2
  banners: ^0.3.1
  rate: ^0.0.2
  fluttertoast: ^8.2.6
  badges: ^3.1.1
  #permission_handler: ^11.3.1
  loading_animation_widget: ^1.2.0+4
  persistent_bottom_nav_bar: ^5.0.2
  another_stepper: ^1.2.2
  country_flags: ^2.1.0
  dio: ^5.4.3+1

  dotted_border: ^2.0.0
  intl_phone_field: ^3.2.0
  dart_code_metrics: ^4.18.0
  flutter_chat_bubble: ^2.0.2
  flutter_phone_direct_caller: ^2.1.1
  firebase_messaging: ^14.9.1
  firebase_core: ^2.32.0
  agora_rtc_engine: ^6.3.2
  agora_uikit: ^1.3.10
  chat_bubbles: ^1.6.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  modal_progress_hud_nsn: ^0.5.1
  firebase_storage: ^11.7.7
  video_player: ^2.8.7
  #flutter_sound: ^9.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/translations/

  fonts:
    - family: Itim
      fonts:
        - asset: assets/fonts/Itim-Regular.ttf
